name: Set Specific Package Version and Create Pull Request

on:
  repository_dispatch:
    types: [update-package-version]

permissions:
  contents: write
  pull-requests: write

jobs:
  set-package-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.client_payload.branch_name }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.1'

    - name: Create a new branch
      run: |
        git checkout -b ${{ github.event.client_payload.branch_name }}_pkg_update

    - name: Install Specific Package Version
      run: npm install ${{ github.event.client_payload.package_name }}@${{ github.event.client_payload.package_version }}

    - name: Commit changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git checkout ${{ github.event.client_payload.branch_name }}_pkg_update
        git add .
        git commit -m "Set ${{ github.event.client_payload.package_name }} to version ${{ github.event.client_payload.package_version }}"
        git push origin ${{ github.event.client_payload.branch_name }}_pkg_update

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.event.client_payload.branch_name }}_pkg_update
        commit-message: "Set ${{ github.event.client_payload.package_name }} to version ${{ github.event.client_payload.package_version }}"
        title: "Set ${{ github.event.client_payload.package_name }} to version ${{ github.event.client_payload.package_version }}"
        body: "This pull request sets ${{ github.event.client_payload.package_name }} to version ${{ github.event.client_payload.package_version }}."
        base: ${{ github.event.client_payload.branch_name }}
