name: Set Specific Package Version and Create Pull Request

on:
  repository_dispatch:
    types: [update-package-version]

permissions:
  contents: write

jobs:
  set-package-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the original branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: Generate a unique branch name using timestamp
        id: vars
        run: echo "branch_name=${{ github.event.client_payload.branch_name }}_pkg_update_$(date +%s)" >> $GITHUB_ENV

      - name: Create a new branch
        run: |
          git checkout -b "${{ env.branch_name }}"

      - name: Install Specific Package Version
        run: npm install "${{ github.event.client_payload.package_name }}@${{ github.event.client_payload.package_version }}"

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Set ${{ github.event.client_payload.package_name }} to version ${{ github.event.client_payload.package_version }}"
          git push origin "${{ env.branch_name }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "${{ env.branch_name }}"
          commit-message: "Set ${{ github.event.client_payload.package_name }} to version ${{ github.event.client_payload.package_version }}"
          title: "Set ${{ github.event.client_payload.package_name }} to version ${{ github.event.client_payload.package_version }}"
          body: "This pull request sets ${{ github.event.client_payload.package_name }} to version ${{ github.event.client_payload.package_version }}."
          base: ${{ github.event.client_payload.branch_name }}
          branch-suffix: ''
