name: Set Specific Package Version and Create Pull Request

on:
  repository_dispatch:
    types: [update-package-version]

permissions:
  contents: write
  pull-requests: write

jobs:
  set-package-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the original branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: Generate a unique branch name using timestamp
        id: vars
        run: echo "branch_name=${{ github.event.client_payload.branch_name }}_pkg_update_$(date +%s)" >> $GITHUB_ENV

      - name: Create a new branch
        run: |
          git checkout -b "${{ env.branch_name }}"

      - name: Install Specific Package Version
        run: |
          echo "Current branch: $(git branch --show-current)"
          npm install "${{ github.event.client_payload.package_name }}@${{ github.event.client_payload.package_version }}" --save-exact

      - name: Commit changes
        run: |
          git add .
          git commit -m "Set ${{ github.event.client_payload.package_name }} to version ${{ github.event.client_payload.package_version }}"
          git push origin "${{ env.branch_name }}"

      - name: Create Pull Request using GitHub API
        run: |
          pr_data=$(cat <<EOF
          {
            "title": "Set ${{ github.event.client_payload.package_name }} to version ${{ github.event.client_payload.package_version }}",
            "head": "${{ env.branch_name }}",
            "base": "${{ github.event.client_payload.branch_name }}",
            "body": "This pull request sets ${{ github.event.client_payload.package_name }} to version ${{ github.event.client_payload.package_version }}.",
            "maintainer_can_modify": true
          }
          EOF
          )
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "$pr_data"
