name: Set Specific Package Version and Create Pull Request

on:
  repository_dispatch:
    types: [update-package-version]

permissions:
  contents: write
  pull-requests: write

jobs:
  set-package-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the original branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: Generate a unique branch name using timestamp
        id: vars
        run: echo "new_branch_name=${{ github.event.client_payload.branch_name }}_pkg_update_$(date +%s)" >> $GITHUB_ENV

      - name: Install Specific Package Version
        run: |
          npm install "${{ github.event.client_payload.package_name }}@${{ github.event.client_payload.package_version }}" --save-exact

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "${{ env.new_branch_name }}"
          base: ${{ github.event.client_payload.branch_name }}
          commit-message: "Update ${{ github.event.client_payload.package_name }} to version ${{ github.event.client_payload.package_version }}"
          title: "Set ${{ github.event.client_payload.package_name }} to version ${{ github.event.client_payload.package_version }}"
          body: "This pull request sets ${{ github.event.client_payload.package_name }} to version ${{ github.event.client_payload.package_version }}."
